"""
Author: Susheel Bhanu BUSI
Affiliation: Molecular Ecology group, UKCEH
Date: [2026-06-09]
Run: snakemake -s workflow/Snakefile --configfile config/config.yaml --use-conda --cores 4 -rp
Latest modification:
Purpose: Running metagenomic analyses for the DECODE project
"""


##############################
# MODULES
import os
import re
import glob
import pandas as pd

# importing specific scripts for parsing etc.
# from scripts.utils import find_fast5, assembler_pairs


##############################
# CONFIG
include:
    "rules/init.smk"


##############################
# TARGETS & RULES
# List of (main) targets to be created
TARGETS = []

# Include rules and add targets based on the config file
#include:
#    "rules/setup.smk"
#include:
#    "rules/databases.smk"

# PROFILE
if "extract" in config["steps"]:
    include:
        "rules/extract_16S.smk"
    TARGETS += [
        "status/extract_16S.done"
    ]

# CLUSTER
if "cluster" in config["steps"]:
    include:
        "rules/otu_clustering.smk"
    TARGETS += [
        "status/otu_clustering.done"
    ]

# BIN_INFO
if "bin_info" in config["steps"]:
    include:
        "rules/bin_info.smk"
    include:
        "rules/mag_link.smk"
    TARGETS += [
        "status/bin_info.done",
        "status/mag_link.done"
    ]

# DEREPLICATED MAGS
if "dereplicate" in config["steps"]:
    include:
        "rules/dereplicated_mag_link.smk"
    TARGETS += [
        "status/dereplicated_mag_link.done"
    ]

# COMPARIING WITH GLOBDB and SMAG
if "comparison" in config["steps"]:
    include:
        "rules/compare_globdb.smk"
    TARGETS += [
        "status/compare_globdb.done"
    ]


# MAG ANNOTATIONS (MQ_MAGs_all_0.95)
# CoverM QC + collation
if "coverage_check" in config["steps"]:
    include:
        "rules/coverm_check.smk"
    TARGETS += [
        "status/coverm_check.done"
    ]

# TRAITS (microtrait)
if "traits" in config["steps"]:
    include:
        "rules/microtrait.smk"
    TARGETS += [
        "status/microtrait.done"
    ]

# PORTRAITS (phenotypic trait predictions)
if "portraits" in config["steps"]:
    include:
        "rules/portraits.smk"
    TARGETS += [
        "status/portraits.done"
    ]

# BGCs (antiSMASH + GECCO)
if "bgc" in config["steps"]:
    include:
        "rules/bgc.smk"
    TARGETS += [
        "status/bgc.done"
    ]

# BGC families (BiG-SLiCE on antiSMASH regions; needs the bgc rules)
if "bgc_families" in config["steps"]:
    if "bgc" not in config["steps"]:
        include:
            "rules/bgc.smk"
    include:
        "rules/bgc_families.smk"
    TARGETS += [
        "status/bgc_families.done"
    ]

# MERGE: one table with all MAG annotations (run once the other steps are done)
if "merge" in config["steps"]:
    include:
        "rules/merge.smk"
    TARGETS += [
        "status/merge.done"
    ]

# COMMUNITY ANALYSIS (R): all annotation sets across compartments, treatments and time scales
if "community_analysis" in config["steps"]:
    include:
        "rules/community_analysis.smk"
    TARGETS += [
        "status/community_analysis.done"
    ]

# GENE CATALOGUE: dereplicated + clustered genes from all assemblies, gene-level annotation
if "gene_catalogue" in config["steps"]:
    include:
        "rules/gene_catalogue.smk"
    TARGETS += [
        "status/gene_catalogue.done"
    ]

# AMR (RGI + BacMet)
if "amr" in config["steps"]:
    include:
        "rules/amr.smk"
    TARGETS += [
        "status/amr.done"
    ]


# No targets
if len(TARGETS) == 0:
    raise Exception('You are not serious. Nothing to be done? Really?')

rule all:
    default_target: True    # otherwise the first included rule is the default target
    input:
        TARGETS

